default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: todo
  password: todo
  host: localhost

development:
  <<: *default
  database: todo

test:
  <<: *default
  database: todo_test

staging:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DBNAME'] %>

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DBNAME'] %>